### PR TITLE
Updated README

### PR DESCRIPTION
**Pull request by frederickohen**
Fixed markdown issues.

### CODE REVIEW

**Comment by abbeyjackson** [comment]
Hey @freddieoh thanks for submitting this and helping to clean the file up! The only problem I see is that I had originally each heading at a different priority, not header one, and now they are all at header one. For example Algorithms is a type of course so it's header priority should be lower. Also only the first header should be priority one ("iOS-Learning-Resources") then the ones that follow were header priority two.

I think instead of deleting the "##"'s they just needed a space inserted before the first letter on the line.

screen shot 2018-01-18 at 8 40 37 am

**Comment by frederickohen** [comment]
Sounds good, I'll work on it with the appropriate edits!

**Comment by frederickohen** [comment]
Check out the new edits and let me know what you think.

**Comment by abbeyjackson** [comment]
@freddieoh sorry I never handled this. I have just invited you as a collaborator to this repo. You'll have push access and can make changes you'd like. Feel free to make any changes and additions without consulting me. The only thing I ask is that you maintain the idea that the list is not a catch all for every single blog website out there and only high quality resources should be added.

**Pull request merged**
